Changelog and pipeline improvements

diff --git a/.github/workflows/snapshot.yml b/.github/workflows/snapshot.yml
--- a/.github/workflows/snapshot.yml
+++ b/.github/workflows/snapshot.yml
@@ -33,6 +33,20 @@ jobs:
       - uses: actions/checkout@v5
         with:
           fetch-depth: 0
+      - name: Check if CHANGELOG.md was updated
+        if: github.ref != 'refs/heads/main'
+        run: |
+          if [ "${{ github.event_name }}" == "pull_request" ]; then
+            BASE="origin/${{ github.base_ref }}"
+          else
+            BASE="origin/main"
+          fi
+
+          echo "Comparing against $BASE"
+          if git diff --quiet $BASE...HEAD -- CHANGELOG.md; then
+            echo "::error::CHANGELOG.md was not updated in this branch/PR. Please add an entry to the CHANGELOG."
+            exit 1
+          fi
       - uses: actions/setup-node@v4
         with:
           node-version: 24
@@ -90,3 +104,11 @@ jobs:
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Build and release
         run: make build-snapshot PR_ID=${{ github.event.pull_request.number }}
+      - name: Update GitHub Pre-release
+        if: github.ref == 'refs/heads/main'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          RAW_DIGEST=$(docker buildx imagetools inspect dillmann/nginx-ignition:snapshot --format '{{.manifest.digest}}')
+          DOCKER_IMAGE_HASH=$(echo $RAW_DIGEST | sed 's/:/-/g')
+          ./.github/scripts/update-release.sh "$DOCKER_IMAGE_HASH" "true"
